### ISSUE TITLE
Poetry fails to install beanprice dependency

### ISSUE THREAD

**Issue by sclu1034** [beancount/beangrow#33]
Poetry (running v1.8.4) does not understand `git+https://` URLs and throws "ssh: Could not resolve hostname git+https: Name or service not known".

Looking at https://python-poetry.org/docs/dependency-specification/#git-dependencies, simply `https://` would be correct.

**Comment by blais** [comment]
Send me a patch I don't use poetry.
Thank you,

**Comment by sclu1034** [comment]
> I don't use poetry.

There's a `poetry.toml` and `poetry.lock` in this repo, though.
But I don't have experience with it either, the initial error for me was from a `pip install -r requirements.txt` with `git+https://github.com/beancount/beangrow.git` leading to

```
ERROR: Could not install packages due to an OSError: No connection adapters were found for 'git+git+https://github.com/beancount/beanprice.git'
```

My guess for a patch would be 

```diff
-beanprice = {git = "git+https://github.com/beancount/beanprice.git"}
+beanprice = {git = "https://github.com/beancount/beanprice.git"}
```

in `pyproject.toml`
